# Generated by Django 6.1.1 on 2026-10-02 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_count', models.PositiveSmallIntegerField()),
                ('prize_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='draws.drawentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('provider_payout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='winners.drawwinner')),
            ],
            options={
                'ordering': ('winner', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='WinnerProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(default='winner-proofs', max_length=100)),
                ('object_path', models.CharField(max_length=500)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_winner_proofs', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proofs', to='winners.drawwinner')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='drawwinner',
            index=models.Index(fields=['verification_status', 'created_at'], name='winner_verification_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawwinner',
            constraint=models.UniqueConstraint(fields=('entry', 'match_count'), name='winner_entry_match_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawwinner',
            constraint=models.CheckConstraint(condition=models.Q(('match_count__in', (3, 4, 5))), name='winner_match_count_ck'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('winner', 'attempt_number'), name='payout_winner_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payout_amount_pos_ck'),
        ),
        migrations.AddIndex(
            model_name='winnerproof',
            index=models.Index(fields=['review_status', 'submitted_at'], name='winner_proof_review_idx'),
        ),
    ]
