# Generated by Django 6.1.1 on 2026-10-02 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_date', models.DateField()),
                ('score', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score_date',),
                'indexes': [models.Index(fields=['user', '-score_date'], name='scores_user_date_desc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 45)), name='scores_score_1_45_ck'), models.UniqueConstraint(fields=('user', 'score_date'), name='scores_user_date_uniq')],
            },
        ),
    ]
