# Generated by Django 6.1.1 on 2026-10-02 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scores', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('mode', models.CharField(choices=[('random', 'Random'), ('algorithmic', 'Algorithmic')], max_length=12)),
                ('candidate_min', models.PositiveSmallIntegerField(default=1)),
                ('candidate_max', models.PositiveSmallIntegerField(default=45)),
                ('number_count', models.PositiveSmallIntegerField(default=5)),
                ('prize_pool_contribution_bps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('candidate_max__gt', models.F('candidate_min'))), name='draw_config_range_ck'), models.CheckConstraint(condition=models.Q(('number_count__gt', 0)), name='draw_config_count_ck'), models.CheckConstraint(condition=models.Q(('prize_pool_contribution_bps__isnull', True), ('prize_pool_contribution_bps__lte', 10000), _connector='OR'), name='draw_config_pool_pct_ck')],
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('eligibility_cutoff', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('simulated', 'Simulated'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='draws.drawconfiguration')),
            ],
            options={
                'ordering': ('-scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='DrawEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_at', models.DateTimeField()),
                ('subscription_snapshot', models.JSONField(blank=True, default=dict)),
                ('score_snapshot', models.JSONField(blank=True, default=list)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='draws.draw')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_entries', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrawEntryNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='draws.drawentry')),
                ('source_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_number_snapshots', to='scores.golfscore')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='DrawPrizeTierConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_count', models.PositiveSmallIntegerField()),
                ('share_bps', models.PositiveSmallIntegerField()),
                ('rollover_unclaimed', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_tiers', to='draws.drawconfiguration')),
            ],
            options={
                'ordering': ('-match_count',),
            },
        ),
        migrations.CreateModel(
            name='DrawRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.PositiveIntegerField()),
                ('run_type', models.CharField(choices=[('simulation', 'Simulation'), ('publish', 'Publish')], max_length=12)),
                ('algorithm_version', models.CharField(max_length=40)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='draws.draw')),
            ],
            options={
                'ordering': ('draw', 'run_number'),
            },
        ),
        migrations.CreateModel(
            name='DrawResultNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_numbers', to='draws.drawrun')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='DrawTierPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_count', models.PositiveSmallIntegerField()),
                ('share_bps', models.PositiveSmallIntegerField()),
                ('available_minor', models.PositiveBigIntegerField(default=0)),
                ('rollover_in_minor', models.PositiveBigIntegerField(default=0)),
                ('rollover_out_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_pools', to='draws.draw')),
            ],
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['status', 'scheduled_at'], name='draws_status_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='draw',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility_cutoff__lte', models.F('scheduled_at'))), name='draws_cutoff_before_run_ck'),
        ),
        migrations.AddIndex(
            model_name='drawentry',
            index=models.Index(fields=['user', 'draw'], name='draw_entry_user_draw_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawentry',
            constraint=models.UniqueConstraint(fields=('draw', 'user'), name='draw_entry_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawentrynumber',
            constraint=models.UniqueConstraint(fields=('entry', 'ordinal'), name='draw_entry_number_pos_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawentrynumber',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 45)), name='draw_entry_number_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawprizetierconfiguration',
            constraint=models.UniqueConstraint(fields=('configuration', 'match_count'), name='draw_tier_config_match_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawprizetierconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('match_count__in', (3, 4, 5))), name='draw_tier_config_match_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawprizetierconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('share_bps__lte', 10000)), name='draw_tier_config_share_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawrun',
            constraint=models.UniqueConstraint(fields=('draw', 'run_number'), name='draw_run_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_published', True)), fields=('draw',), name='draw_one_published_run_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawrun',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('run_type', 'publish'), _connector='OR'), name='draw_published_run_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawresultnumber',
            constraint=models.UniqueConstraint(fields=('run', 'ordinal'), name='draw_result_number_pos_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawresultnumber',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 45)), name='draw_result_number_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawtierpool',
            constraint=models.UniqueConstraint(fields=('draw', 'match_count'), name='draw_pool_match_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drawtierpool',
            constraint=models.CheckConstraint(condition=models.Q(('match_count__in', (3, 4, 5))), name='draw_pool_match_ck'),
        ),
        migrations.AddConstraint(
            model_name='drawtierpool',
            constraint=models.CheckConstraint(condition=models.Q(('share_bps__lte', 10000)), name='draw_pool_share_ck'),
        ),
    ]
