# Generated by Django 6.1.1 on 2026-10-02 16:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-is_featured', 'display_order', 'name'),
                'indexes': [models.Index(fields=['is_active', '-is_featured'], name='charities_active_featured_idx')],
            },
        ),
        migrations.CreateModel(
            name='CharityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='charities.charity')),
            ],
            options={
                'ordering': ('starts_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='charities_event_time_ck')],
            },
        ),
        migrations.CreateModel(
            name='CharitySelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_bps', models.PositiveSmallIntegerField(default=1000)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='charities.charity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_from',),
                'indexes': [models.Index(fields=['user', '-effective_from'], name='charity_user_effective_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('contribution_bps__gte', 1000), ('contribution_bps__lte', 10000)), name='charity_selection_pct_ck'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='charity_selection_period_ck'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('user',), name='charity_one_current_sel_uniq')],
            },
        ),
    ]
